
export const LOADING_STATUS = 'LOADING_STATUS'

export const FETCH_MOVIE_LIST_REQUEST = 'REQUEST_MOVIE_LIST_REQUEST'
export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS'
// export const FETCH_MOVIE_LIST_FAILURE = 'FETCH_MOVIE_LIST_FAILURE'

export const FETCH_MOVIE_LIST = {
    REQUEST: 'FETCH_MOVIE_LIST_REQUEST',
    SUCCESS: 'FETCH_MOVIE_LIST_SUCCESS',
    FAILURE: 'FETCH_MOVIE_LIST_FAILURE'
};

export const FETCH_MOVIE = {
    REQUEST: 'FETCH_MOVIE_REQUSET',
    SUCCESS: 'FETCH_MOVIE_SUCCESS',
    FAILURE: 'FETCH_MOVIE_FAILURE'
};

export const SEARCH_MOVIE = {
    REQUEST: 'SEARCH_MOVIE_REQUEST',
    SUCCESS: 'SEARCH_MOVIE_SUCCESS',
    FAILURE: 'SEARCH_MOVIE_FAILURE'
}

export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR'

