

export const FETCH_MOVIE_LIST_REQUEST = 'REQUEST_MOVIE_LIST_REQUEST'
export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS'
// export const FETCH_MOVIE_LIST_FAILURE = 'FETCH_MOVIE_LIST_FAILURE'

